### ISSUE TITLE
Why Either?

### ISSUE THREAD

**Issue by danwdart** [MichelBoucey/NanoID#1]
Hello,

Why do you return ```nanoID :: IO (Either String NanoID) ```?

I couldn't find any reference to this erroring / using `Left`, although I may be being blind, so is that necessary?

Thanks

**Comment by MichelBoucey** [comment]
Hello,

Thanks for your feedback, Dan.

At first glance, yes, it is necessary. Because `customNanoID` can accept a bad argument for the nanoid length, like `Just (-1)`, so `nanoID` too. But, indeed, the monadic `fail` that I use in this function already throws an exception. I have removed `Either` and `fail`. I now use [Natural](https://hackage.haskell.org/package/base-4.12.0.0/docs/Numeric-Natural.html) instead of `Int`, which rise an exception too. I have pushed those changes in `nanoid-3.0.0`.

In Haskell, `Either` is generally used as I do. Its _`Right`_ branch is used as the _right_ answer, or success. And its `Left`branch is used to carry a bad answer, a message error. The `Left` branch is used as failure branch.

**Comment by danwdart** [comment]
Thanks, it's not that I don't understand the use of `Either` generally, it's more that I didn't see either a `Left` or `fail` in that specific function or any that it called in v2 but I now see that there was indeed a `fail` in one it called, and I was indeed being blind.

Now though in v3, it looks a lot simpler anyway.

Thanks!

**Comment by MichelBoucey** [comment]
Yes it's cleaner now. Thanks.
